//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.RegulatorService.Frontend.Web.Resources.Views.RemoveApprovedUser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RemovedConfirmation_cy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemovedConfirmation_cy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.RegulatorService.Frontend.Web.Resources.Views.RemoveApprovedUser.RemovedConfi" +
                            "rmation.cy", typeof(RemovedConfirmation_cy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WThe organisation has not nominated a new approved person. They cannot submit packaging data..
        /// </summary>
        internal static string Confirmation_Text_1 {
            get {
                return ResourceManager.GetString("Confirmation.Text.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYou need to ask the organisation to contact the service desk to nominate a new approved person..
        /// </summary>
        internal static string Confirmation_Text_2 {
            get {
                return ResourceManager.GetString("Confirmation.Text.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWhat happens next.
        /// </summary>
        internal static string Page_Heading {
            get {
                return ResourceManager.GetString("Page.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WApproved person removed.
        /// </summary>
        internal static string Page_Panel {
            get {
                return ResourceManager.GetString("Page.Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYou have selected {0} to be removed from {1} account.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
    }
}
