trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: 'EPR.RegulatorService.Frontend.Web'
  - name: testProjectFolder
    value: 'EPR.RegulatorService.Frontend.UnitTests'
  - name: sonarQubeProjectKey
    value: epr-regulator-service
  - name: sonarQubeProjectName
    value: epr-regulator-service
  - name: runNugetTasks
    value: true
  - name: runTests
    value: true
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      endpoint: defra
      ref: main

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ variables.runTests }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    dotnetVersion: ${{ variables.dotnetVersion }}
