trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'

parameters:
- name: runTests
  displayName: Run tests
  type: boolean
  default: true
- name: runOWASPScan
  displayName: Run OWASP Scan
  type: boolean
  default: true
- name: sonarqubeInstance
  displayName: 'Select SonarQube for v9.9 or SonarQubeLatest for 10.4'
  type: string
  default: 'SonarQubeLatest'
  values:
  - 'SonarQube'
  - 'SonarQubeLatest'

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: 'EPR.RegulatorService.Frontend.Web'
  - name: testProjectFolder
    value: 'EPR.RegulatorService.Frontend.UnitTests'
  - name: sonarQubeProjectKey
    value: epr-regulator-service
  - name: sonarQubeProjectName
    value: epr-regulator-service
  - name: runNugetTasks
    value: true
  - name: dotnetVersion
    value: dotnetVersion8

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      endpoint: defra
      ref: feature/529865-sq-task-tidy

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ parameters.runTests }}
    runOWASPScan: ${{ parameters.runOWASPScan }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
    dotnetVersion: ${{ variables.dotnetVersion }}
