trigger: none
pr: none
pool: DEFRA-COMMON-ubuntu2004-SSV3
appendCommitMessageToRunName: false
name: Path-To-Prod epr-regulator-service

variables:
  azureSubscription: AZD-RWD-DEV1

parameters:
- name: serviceName
  displayName: Select the service to deploy
  type: string
  values:
    - epr-regulator-service

- name: imageTag
  displayName: Enter Tag for the Image (Docker tag)
  default: ''
  type: string

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      endpoint: defra
      ref: main

steps:
  - template: get-current-dockertag.yaml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
      serviceName: ${{ parameters.serviceName }}