trigger: none
pr: none
pool: DEFRA-COMMON-ubuntu2004-SSV3
appendCommitMessageToRunName: false
name: Path-To-Prod epr-regulator-service

variables:
  azureSubscription: AZD-RWD-DEV1

parameters:
- name: serviceName
  displayName: Select the service to deploy
  type: string
  values:
    - DEVRWDWEBWA1411

- name: imageTag
  displayName: Enter Tag for the Image (Docker tag)
  default: ''
  type: string

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      endpoint: defra
      ref: main

steps:
  - task: AzureCLI@2
    displayName: Current Docker Image Tag ${{ parameters.serviceName }}
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Set-StrictMode -Version 3.0
        Set-PSDebug -Trace 1

        $serviceName = "${{ parameters.serviceName }}".ToUpper()
        $currentImageTag = ""

        if ($serviceName -match "RWDWEBWA") {            
          $currentImageTag = az webapp list --query "[?name=='$serviceName']" | jq -r '.[].siteConfig.linuxFxVersion'
        } elseif ($serviceName -match "RWDWEBFA") {
          $currentImageTag = az functionapp list --query "[?name=='$serviceName']" | jq -r '.[].siteConfig.linuxFxVersion'
        } else {
          Write-Error "Unknown Service Type"
          exit 1
        }

        Write-Host ("Current Image Tag for {0}: {1}" -f $serviceName, $currentImageTag)
        Write-Host "##vso[task.setvariable variable=currentImageTag;]$currentImageTag"

  - bash: |
      echo "Current dockerImage for "${{ upper(parameters.serviceName) }}" --> $(currentImageTag)"
      echo "Deploying dockerImage --> "${{ parameters.registryName }}:${{ parameters.imageTag }} "to env --> "${{ parameters.targetEnvironment }}
      echo "Deploying dockerImage to "${{ upper(parameters.serviceName) }}
    displayName: 'Show Environment Details'
  
  - task: AzureCLI@2
    displayName: Check Image Tag '${{ parameters.imageTag }}' exists
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az acr repository show --name devrwdinfac1401 --image eprregulatorfrontendregistry:${{ parameters.imageTag }} --output none 2>$null

        if ($LASTEXITCODE -ne 0) {
          Write-Error "❌ ACR image '$acrName/$image' does not exist (or is not accessible). Failing pipeline."
          exit 1
        }

        Write-Host "✅ Found ACR image: devrwdinfac1401/eprregulatorfrontendregistry:${{ parameters.imageTag }}"
