trigger: none
pr: none
pool: DEFRA-COMMON-ubuntu2004-SSV3
appendCommitMessageToRunName: false
name: 'Path-To-Prod epr-regulator-service'

parameters:
- name: imageTag
  displayName: Enter Tag for the Image (Docker tag) or Release name (Git repo tag)
  default: ''
  type: string


