//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailSentToNominatedApprovedPerson_cy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailSentToNominatedApprovedPerson_cy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson.EmailSe" +
                            "ntToNominatedApprovedPerson.cy", typeof(EmailSentToNominatedApprovedPerson_cy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOnce {0} has created an account, you need to accept or reject it..
        /// </summary>
        internal static string Confirmation_AfterAccountCreated_AcceptOrRejectAccount {
            get {
                return ResourceManager.GetString("Confirmation.AfterAccountCreated.AcceptOrRejectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIf {0} does not apply to be an approved user, you will need to contact them..
        /// </summary>
        internal static string Confirmation_DoesNotApplyToBeApprovedUser_ContactThem {
            get {
                return ResourceManager.GetString("Confirmation.DoesNotApplyToBeApprovedUser.ContactThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWe&apos;ve sent an email to {0} asking them to apply to be an approved person for {1}..
        /// </summary>
        internal static string Page_Heading {
            get {
                return ResourceManager.GetString("Page.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEmail sent to nominated approved person.
        /// </summary>
        internal static string Page_Panel {
            get {
                return ResourceManager.GetString("Page.Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWhat you need to do next.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
    }
}
