//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnterPersonEmail_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnterPersonEmail_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson.EnterPe" +
                            "rsonEmail.en", typeof(EnterPersonEmail_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email will be sent to them telling them how to apply to be a nominated person. You will need to accept or reject their application..
        /// </summary>
        internal static string Email_HintText {
            get {
                return ResourceManager.GetString("Email.HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email_Label {
            get {
                return ResourceManager.GetString("Email.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem.
        /// </summary>
        internal static string ErrorSummary_Title {
            get {
                return ResourceManager.GetString("ErrorSummary.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email in the correct format, like name@example.com.
        /// </summary>
        internal static string ErrorTitle_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorTitle.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address must be 254 characters or less.
        /// </summary>
        internal static string ErrorTitle_InvalidEmailLength {
            get {
                return ResourceManager.GetString("ErrorTitle.InvalidEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter their email address.
        /// </summary>
        internal static string ErrorTitle_NullEmail {
            get {
                return ResourceManager.GetString("ErrorTitle.NullEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is their email address?.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email in the correct format, like name@example.com.
        /// </summary>
        internal static string PersonEmail_InvalidFormat {
            get {
                return ResourceManager.GetString("PersonEmail.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter their email address.
        /// </summary>
        internal static string PersonEmail_MissingError {
            get {
                return ResourceManager.GetString("PersonEmail.MissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address must be 254 characters or less.
        /// </summary>
        internal static string PersonEmail_TooLongError {
            get {
                return ResourceManager.GetString("PersonEmail.TooLongError", resourceCulture);
            }
        }
    }
}
