//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnterPersonName_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnterPersonName_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson.EnterPe" +
                            "rsonName_en", typeof(EnterPersonName_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
        
        internal static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName.Label", resourceCulture);
            }
        }
        
        internal static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName.Label", resourceCulture);
            }
        }
        
        internal static string ErrorSummary_Title {
            get {
                return ResourceManager.GetString("ErrorSummary.Title", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_FirstNameNull {
            get {
                return ResourceManager.GetString("ErrorTitle.FirstNameNull", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_FirstNameDigits {
            get {
                return ResourceManager.GetString("ErrorTitle.FirstNameDigits", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_FirstNameLength {
            get {
                return ResourceManager.GetString("ErrorTitle.FirstNameLength", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_LastNameNull {
            get {
                return ResourceManager.GetString("ErrorTitle.LastNameNull", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_LastNameDigits {
            get {
                return ResourceManager.GetString("ErrorTitle.LastNameDigits", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_LastNameLength {
            get {
                return ResourceManager.GetString("ErrorTitle.LastNameLength", resourceCulture);
            }
        }
    }
}
