//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnterPersonEmail_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnterPersonEmail_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EPR.RegulatorService.Frontend.Web.Resources.Views.InviteNewApprovedPerson.EnterPe" +
                            "rsonEmail_en", typeof(EnterPersonEmail_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
        
        internal static string Email_HintText {
            get {
                return ResourceManager.GetString("Email.HintText", resourceCulture);
            }
        }
        
        internal static string ErrorSummary_Title {
            get {
                return ResourceManager.GetString("ErrorSummary.Title", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_NullEmail {
            get {
                return ResourceManager.GetString("ErrorTitle.NullEmail", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_InvalidEmail {
            get {
                return ResourceManager.GetString("ErrorTitle.InvalidEmail", resourceCulture);
            }
        }
        
        internal static string ErrorTitle_InvalidEmailLength {
            get {
                return ResourceManager.GetString("ErrorTitle.InvalidEmailLength", resourceCulture);
            }
        }
        
        internal static string Email_Label {
            get {
                return ResourceManager.GetString("Email.Label", resourceCulture);
            }
        }
    }
}
