variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprregulatorfrontendregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprregulatorfrontendregistry'
  serviceName: 'prdrwdwebwa1411'
  resourceGroupName: 'prdrwdwebrg1401'
